// Code generated by MockGen. DO NOT EDIT.
// Source: account.go

// Package mock_factory is a generated GoMock package.
package mock_factory

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	aggregate "github.com/illusory-server/accounts/internal/domain/aggregate"
)

// MockAccountFactory is a mock of AccountFactory interface.
type MockAccountFactory struct {
	ctrl     *gomock.Controller
	recorder *MockAccountFactoryMockRecorder
}

// MockAccountFactoryMockRecorder is the mock recorder for MockAccountFactory.
type MockAccountFactoryMockRecorder struct {
	mock *MockAccountFactory
}

// NewMockAccountFactory creates a new mock instance.
func NewMockAccountFactory(ctrl *gomock.Controller) *MockAccountFactory {
	mock := &MockAccountFactory{ctrl: ctrl}
	mock.recorder = &MockAccountFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountFactory) EXPECT() *MockAccountFactoryMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockAccountFactory) CreateAccount(firstName, lastName, email, nick, password string) (*aggregate.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", firstName, lastName, email, nick, password)
	ret0, _ := ret[0].(*aggregate.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockAccountFactoryMockRecorder) CreateAccount(firstName, lastName, email, nick, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockAccountFactory)(nil).CreateAccount), firstName, lastName, email, nick, password)
}
