// Code generated by MockGen. DO NOT EDIT.
// Source: account.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	account "github.com/illusory-server/accounts/internal/app/usecase/account"
	aggregate "github.com/illusory-server/accounts/internal/domain/aggregate"
	vo "github.com/illusory-server/accounts/internal/domain/vo"
)

// MockTimer is a mock of Timer interface.
type MockTimer struct {
	ctrl     *gomock.Controller
	recorder *MockTimerMockRecorder
}

// MockTimerMockRecorder is the mock recorder for MockTimer.
type MockTimerMockRecorder struct {
	mock *MockTimer
}

// NewMockTimer creates a new mock instance.
func NewMockTimer(ctrl *gomock.Controller) *MockTimer {
	mock := &MockTimer{ctrl: ctrl}
	mock.recorder = &MockTimerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimer) EXPECT() *MockTimerMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockTimer) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockTimerMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockTimer)(nil).Now))
}

// MockAccount is a mock of Account interface.
type MockAccount struct {
	ctrl     *gomock.Controller
	recorder *MockAccountMockRecorder
}

// MockAccountMockRecorder is the mock recorder for MockAccount.
type MockAccountMockRecorder struct {
	mock *MockAccount
}

// NewMockAccount creates a new mock instance.
func NewMockAccount(ctrl *gomock.Controller) *MockAccount {
	mock := &MockAccount{ctrl: ctrl}
	mock.recorder = &MockAccountMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccount) EXPECT() *MockAccountMockRecorder {
	return m.recorder
}

// AddAvatarLink mocks base method.
func (m *MockAccount) AddAvatarLink(ctx context.Context, id, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAvatarLink", ctx, id, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAvatarLink indicates an expected call of AddAvatarLink.
func (mr *MockAccountMockRecorder) AddAvatarLink(ctx, id, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAvatarLink", reflect.TypeOf((*MockAccount)(nil).AddAvatarLink), ctx, id, url)
}

// Create mocks base method.
func (m *MockAccount) Create(ctx context.Context, firstName, lastName, email, nick, password string) (*account.WithoutPassword, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, firstName, lastName, email, nick, password)
	ret0, _ := ret[0].(*account.WithoutPassword)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAccountMockRecorder) Create(ctx, firstName, lastName, email, nick, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccount)(nil).Create), ctx, firstName, lastName, email, nick, password)
}

// DeleteById mocks base method.
func (m *MockAccount) DeleteById(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteById", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteById indicates an expected call of DeleteById.
func (mr *MockAccountMockRecorder) DeleteById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteById", reflect.TypeOf((*MockAccount)(nil).DeleteById), ctx, id)
}

// DeleteManyByIds mocks base method.
func (m *MockAccount) DeleteManyByIds(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteManyByIds", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteManyByIds indicates an expected call of DeleteManyByIds.
func (mr *MockAccountMockRecorder) DeleteManyByIds(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteManyByIds", reflect.TypeOf((*MockAccount)(nil).DeleteManyByIds), ctx, ids)
}

// GetByEmail mocks base method.
func (m *MockAccount) GetByEmail(ctx context.Context, email string) (*account.WithoutPassword, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*account.WithoutPassword)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockAccountMockRecorder) GetByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockAccount)(nil).GetByEmail), ctx, email)
}

// GetById mocks base method.
func (m *MockAccount) GetById(ctx context.Context, id string) (*account.WithoutPassword, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(*account.WithoutPassword)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockAccountMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockAccount)(nil).GetById), ctx, id)
}

// GetByIds mocks base method.
func (m *MockAccount) GetByIds(ctx context.Context, ids []string) ([]*account.WithoutPassword, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIds", ctx, ids)
	ret0, _ := ret[0].([]*account.WithoutPassword)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIds indicates an expected call of GetByIds.
func (mr *MockAccountMockRecorder) GetByIds(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIds", reflect.TypeOf((*MockAccount)(nil).GetByIds), ctx, ids)
}

// GetByNickname mocks base method.
func (m *MockAccount) GetByNickname(ctx context.Context, nickname string) (*account.WithoutPassword, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByNickname", ctx, nickname)
	ret0, _ := ret[0].(*account.WithoutPassword)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByNickname indicates an expected call of GetByNickname.
func (mr *MockAccountMockRecorder) GetByNickname(ctx, nickname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByNickname", reflect.TypeOf((*MockAccount)(nil).GetByNickname), ctx, nickname)
}

// GetByQuery mocks base method.
func (m *MockAccount) GetByQuery(ctx context.Context, query vo.Query) ([]*account.WithoutPassword, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByQuery", ctx, query)
	ret0, _ := ret[0].([]*account.WithoutPassword)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByQuery indicates an expected call of GetByQuery.
func (mr *MockAccountMockRecorder) GetByQuery(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByQuery", reflect.TypeOf((*MockAccount)(nil).GetByQuery), ctx, query)
}

// GetWithPasswordById mocks base method.
func (m *MockAccount) GetWithPasswordById(ctx context.Context, id string) (*aggregate.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithPasswordById", ctx, id)
	ret0, _ := ret[0].(*aggregate.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithPasswordById indicates an expected call of GetWithPasswordById.
func (mr *MockAccountMockRecorder) GetWithPasswordById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithPasswordById", reflect.TypeOf((*MockAccount)(nil).GetWithPasswordById), ctx, id)
}

// UpdateEmailById mocks base method.
func (m *MockAccount) UpdateEmailById(ctx context.Context, id, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmailById", ctx, id, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmailById indicates an expected call of UpdateEmailById.
func (mr *MockAccountMockRecorder) UpdateEmailById(ctx, id, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmailById", reflect.TypeOf((*MockAccount)(nil).UpdateEmailById), ctx, id, email)
}

// UpdateInfoById mocks base method.
func (m *MockAccount) UpdateInfoById(ctx context.Context, id, firstName, lastName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInfoById", ctx, id, firstName, lastName)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInfoById indicates an expected call of UpdateInfoById.
func (mr *MockAccountMockRecorder) UpdateInfoById(ctx, id, firstName, lastName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInfoById", reflect.TypeOf((*MockAccount)(nil).UpdateInfoById), ctx, id, firstName, lastName)
}

// UpdateNickById mocks base method.
func (m *MockAccount) UpdateNickById(ctx context.Context, id, nick string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNickById", ctx, id, nick)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNickById indicates an expected call of UpdateNickById.
func (mr *MockAccountMockRecorder) UpdateNickById(ctx, id, nick interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNickById", reflect.TypeOf((*MockAccount)(nil).UpdateNickById), ctx, id, nick)
}

// UpdatePasswordById mocks base method.
func (m *MockAccount) UpdatePasswordById(ctx context.Context, id, oldPassword, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePasswordById", ctx, id, oldPassword, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePasswordById indicates an expected call of UpdatePasswordById.
func (mr *MockAccountMockRecorder) UpdatePasswordById(ctx, id, oldPassword, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasswordById", reflect.TypeOf((*MockAccount)(nil).UpdatePasswordById), ctx, id, oldPassword, password)
}

// UpdateRoleById mocks base method.
func (m *MockAccount) UpdateRoleById(ctx context.Context, id, role string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoleById", ctx, id, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRoleById indicates an expected call of UpdateRoleById.
func (mr *MockAccountMockRecorder) UpdateRoleById(ctx, id, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoleById", reflect.TypeOf((*MockAccount)(nil).UpdateRoleById), ctx, id, role)
}
